### ISSUE TITLE
Component: PE

### ISSUE THREAD

**Issue by asultan123** [Sparkles-Qemu/qemu_system_integration#2]
Create a separate component branch from the master and develop a PE Component using the baseline project that does a multiply and accumulate operation over two inputs (pixelIn, partialSum) and a local variable. In addition to the ports associated with the actual computation, the PE must have ports for clk, enable and reset. The PE can store the local variable automagically (ie, you don’t have to pass it on explicitly with via an input port). Remember, all systemC components are ultimately structs so you can access member variables as in regular c++. The function governing the output of the PE is defined by the following equation: 

out = input*(local variable)+partialSum

The function is evaluated once every clock cycle. 

Make sure that the PE is reset properly to allow it to return to a known state when the reset is raised to high. (Test for that in the test bench)

An automated test bench should be created that provides a stimulus to the pe and monitors the output. The monitor should verify that the output of the PE is correct. This step may seem tedious but the piece of mind associated with having it available when further modifications are done to the PE is nice. 

Nice to have: 
1) Explore the prospect of using template structs to allow arbitrary precision ports. 
2) Extend the test bench so that it reruns the stimulus post reset to make sure everything still works.

**Comment by walter1999** [comment]
Finish the multiply and accumulate unit. The module contains its own test bench that tests different partialSum and different pixels. The test bench can be expended to include different weights. As now everything seems to be working

**Comment by walter1999** [comment]
I committed all the code to my own branch: walter_test. In this branch I created a folder called MultiplyAndAccumulate. The module that I added is in maa.cpp
